# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classifier.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='classifier.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10\x63lassifier.proto\"\x15\n\x05Image\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x15\n\x05\x42reed\x12\x0c\n\x04name\x18\x01 \x03(\t2<\n\x16\x42reedClassifierService\x12\"\n\x0eRecognizeBreed\x12\x06.Image\x1a\x06.Breed\"\x00\x62\x06proto3'
)




_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='Image.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=41,
)


_BREED = _descriptor.Descriptor(
  name='Breed',
  full_name='Breed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Breed.name', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=64,
)

DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['Breed'] = _BREED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'classifier_pb2'
  # @@protoc_insertion_point(class_scope:Image)
  })
_sym_db.RegisterMessage(Image)

Breed = _reflection.GeneratedProtocolMessageType('Breed', (_message.Message,), {
  'DESCRIPTOR' : _BREED,
  '__module__' : 'classifier_pb2'
  # @@protoc_insertion_point(class_scope:Breed)
  })
_sym_db.RegisterMessage(Breed)



_BREEDCLASSIFIERSERVICE = _descriptor.ServiceDescriptor(
  name='BreedClassifierService',
  full_name='BreedClassifierService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=66,
  serialized_end=126,
  methods=[
  _descriptor.MethodDescriptor(
    name='RecognizeBreed',
    full_name='BreedClassifierService.RecognizeBreed',
    index=0,
    containing_service=None,
    input_type=_IMAGE,
    output_type=_BREED,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BREEDCLASSIFIERSERVICE)

DESCRIPTOR.services_by_name['BreedClassifierService'] = _BREEDCLASSIFIERSERVICE

# @@protoc_insertion_point(module_scope)
