# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import classifier_pb2 as classifier__pb2


class BreedClassifierServiceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecognizeBreed = channel.unary_unary(
                '/BreedClassifierService/RecognizeBreed',
                request_serializer=classifier__pb2.Image.SerializeToString,
                response_deserializer=classifier__pb2.Breed.FromString,
                )


class BreedClassifierServiceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def RecognizeBreed(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BreedClassifierServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecognizeBreed': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeBreed,
                    request_deserializer=classifier__pb2.Image.FromString,
                    response_serializer=classifier__pb2.Breed.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BreedClassifierService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BreedClassifierService(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def RecognizeBreed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BreedClassifierService/RecognizeBreed',
            classifier__pb2.Image.SerializeToString,
            classifier__pb2.Breed.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
