port: 5555
db:
    host: localhost
    user: postgres
    password: postgres
    database: postgres
    max_connections: 50
lost:
    itemsPerPage: 9
    files:
        directory: ./files/lost
        max_size: 10 # MB
