port: 8080
db:
  host: localhost
  user: postgres
  password: postgres
  database: postgres
  max_connections: 50
lost:
  itemsPerPage: 9
  files:
    directory: ./files/lost
    max_size: 10 # MB
  open_id: 1
  close_id: 2
  page_capacity: 4
found:
  page_capacity: 12
  files:
    directory: ./files/found
    max_size: 10 # MB
  open_id: 1
  close_id: 2
profile:
  lost:
    page_capacity: 4
  found:
    page_capacity: 4
breed_srv:
  address: http://shumak.fail/breed