port: 8080
db:
  host: localhost
  user: postgres
  password: postgres
  database: postgres
  max_connections: 50
lost:
  itemsPerPage: 9
  files:
    directory: ./files/lost
    max_size: 10 # MB
  page_capacity: 4
found:
  files:
    directory: ./files/found
    max_size: 10 # MB
  page_capacity: 4
profile:
  lost:
    page_capacity: 4
  found:
    page_capacity: 4
breed_srv:
  address: shumak.fail:80
  conn_timeout: 10
  recognize_timeout: 90